name: RUNPY


on:
 workflow_dispatch:


jobs:
  build:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3

       - name: Set Up Python 3.9
         uses: actions/setup-python@v3
         with:
              python-version: "3.9"

       - name: Updating PIP
         run: python -m pip install --upgrade pip

       - name: Installing Requirements Module
         run: python -m pip install -r requirements.txt

       - name: Running Python File
         env:
           ADMIN_USER_ID: ${{ secrets.ADMIN_USER_ID }}
           BOT_API_TOKEN: ${{ secrets.BOT_API_TOKEN }}
         run: python Bot.py
